remote_theme: pmarsceill/just-the-docs
title: OBADA
description: The Open Blockchain for Asset Disposition Architecture
color_scheme: dark


---
layout: default
title: theobadastandard.md
nav_order: 2
has_children: true
---

---
layout: nested
title: tableofcontents.md
parent: theobadastandard.md
nav_order: 2
---


+-- ..
|-- readme.md
|
|-- theobadastandard.md
|   |-- tableofcontents.md
|
+-- ..
