remote_theme: pmarsceill/just-the-docs
title: TEST WEBSITE 
description: The Open Blockchain for Asset Disposition Architecture
search_enabled: true
footer_content: "Copyright &copy; 2017-2021 Open Blockchain for Asset Disposition Alliance (OBADA)"



---
layout: default
title: theobadastandard.md
nav_order: 2
has_children: true
---

---
layout: nested
title: tableofcontents.md
parent: theobadastandard.md
nav_order: 2
---


+-- ..
|-- readme.md
|
|-- theobadastandard.md
|   |-- tableofcontents.md
|
+-- ..
